kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple1"
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple2"
        - "-listen=:5678"
        
---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - name: apple1
      protocol: TCP
      port: 5678
      targetPort: 5678
   - name: apple2
      protocol: TCP
      port: 5679
      targetPort: 5679
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - ingress.local
    secretName: tls-secret
  rules:
  - host: ingress.local
    http:
      paths:
        - path: /apple1
          backend:
            serviceName: apple-service
            servicePort: 5678
        - path: /apple2
          backend:
            serviceName: apple-service
            servicePort: 5679
